version: '3'

services:
  timescale-test:
    image: timescale/timescaledb:latest-pg15
    container_name: timescale-test
    ports:
      - "5432:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass

volumes:
  timescale-data:
